stages:
    - test

lint-test-job:
    stage: test
    script:
        - echo "Linting code..."
        - composer install # install PHP dependencies
        - vendor/bin/phpcs --standard=PSR2 src/ # run PHP_CodeSniffer
        - vendor/bin/phpmd src/ text codesize,unusedcode,naming # run PHPMD
        - npm install # install JS dependencies
        - npm run lint # run ESLint
        - npx htmlhint index.html # run HTMLHint
        - echo "Linting Complete."